# pywb config file
# ========================================
#
debug: true

# Uncomment to set banner colors and logo
# ui:
  # logo: path/relative/from/static/logo.png
  # logo_home_url: https://example.com
  # navbar_background_hex: 0c49b0
  # navbar_color_hex: fff
  # navbar_light_buttons: true

index_paths: cdx+http://web.archive.org/cdx

collections:
    pywb:
        index_paths: ./sample_archive/cdx/
        archive_paths: ./sample_archive/warcs/

# Enable auto collections
enable_auto_colls: true

# Enable Memento support
enable_memento: true

# Enable remote auto collections
enable_remote_auto_colls: true

# Replay content in an iframe
framed_replay: true

# Enable redirect to exact
redirect_to_exact: true

# Settings for each collection
use_js_obj_proxy: true

# Uncomment and change to set default locale
#default_locale: en

# Uncomment to set available locales
#locales:
#  - en
#  - ru
